# Generated by Django 2.2.5 on 2019-10-03 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('event_type', models.CharField(help_text='Birthday ,  Holiday...', max_length=100)),
                ('event_message', models.CharField(help_text='Dear Customer....', max_length=100)),
            ],
        ),
    ]
