# Generated by Django 2.2.5 on 2019-10-03 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('number', models.IntegerField(verbose_name='Telephone Number')),
                ('phone', models.IntegerField(blank=True, null=True, verbose_name='Telephone 2')),
                ('sex', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], help_text='Gender', max_length=1, verbose_name='Gender')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('birth_date', models.DateField(verbose_name='Date of Birth')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.Business')),
            ],
        ),
    ]
